#! /bin/sh

# hotkeys
sxhkd &

# lemonbar
killall lemonbuddy
lemonbuddy bottom &

bspc config border_width 	2
bspc config normal_border_color '#2A2525'
bspc config active_border_color '#494343'
bspc config focused_border_color '#494343'
bspc config bottom_padding 	22
bspc config window_gap 		10
bspc config single_monocle 	true
# bspc config borderless_monocle 	true
bspc config -m top_padding 	10
bspc config -m bottom_padding 	10
bspc config -m right_padding 	10
bspc config -m left_padding 	10

bspc config split_ratio 		0.5
bspc config focus_follows_pointer 	true

bspc monitor -d 		term web code music games misc

bspc rule -a chromium desktop='web' follow=on
bspc rule -a Firefox desktop='web' follow=on
bspc rule -a google-chrome desktop='web' follow=on
bspc rule -a Atom desktop='code' follow=on
bspc rule -a URxvt state=pseudo_tiled desktop='term' follow=on

bspc rule -a vlc desktop='music' follow=on
bspc rule -a '127.0.0.1__mopify' desktop='music' follow=on

bspc rule -a 'Battle.net.exe' desktop='games' follow=on
bspc rule -a 'Hearthstone.exe' desktop='games' follow=on layer='above'
bspc rule -a 'Wine' desktop='games' follow=on

# show bar below fullscreen
barid=$(xdo id -a bar-bottom)
tries=0
while
  barid=$(xdo id -a bar-bottom)
  [[ -z "$barid" && "$tries" -lt 200 ]]
do
  sleep 0.05
  tries=$((tries+1))
done
[[ "$barid" ]] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$barid"

$CONFIG/priv-bspwm &
