#! /bin/sh

# hotkeys
sxhkd >> $HOME/.logs/sxhkd 2>&1 &

# lemonbar
killall polybar
polybar bottom &

bspc config border_width 	2
bspc config normal_border_color '#2A2525'
bspc config active_border_color '#494343'
bspc config focused_border_color '#494343'
bspc config bottom_padding 	22
bspc config window_gap 		10
bspc config single_monocle 	true

bspc config split_ratio 		0.5
bspc config focus_follows_pointer 	true

bspc monitor -d 		term web code music games misc

bspc rule -a chromium desktop='web'
bspc rule -a Firefox desktop='web' follow=on
bspc rule -a 'google-chrome' desktop='web' follow=on
bspc rule -a 'Google-chrome' desktop='web' follow=on
bspc rule -a 'Chrome-NoFollow' desktop='misc'
bspc rule -a 'Firefox-NoFollow' desktop='misc'
bspc rule -a 'Netflix' desktop='music' follow=on
bspc rule -a Atom desktop='code' follow=on
bspc rule -a Code desktop='code' follow=on
bspc rule -a 'jetbrains-studio' desktop='code' follow=on
bspc rule -a 'jetbrains-idea-ce' desktop='code' follow=on
bspc rule -a 'NetBeans IDE 8.2' desktop='code' follow=on
bspc rule -a 'java-lang-Thread' desktop='code' follow=on
bspc rule -a URxvt state=pseudo_tiled desktop='term' follow=on

bspc rule -a 'Vlc' desktop='music' follow=on
bspc rule -a vlc desktop='music' follow=on
bspc rule -a '127.0.0.1__mopify' desktop='music' follow=on
bspc rule -a 'Spotify' desktop='music' follow=on
bspc rule -a 'Battle.net.exe' desktop='games' follow=on
bspc rule -a 'Hearthstone.exe' desktop='games' follow=on layer='above'
bspc rule -a 'Wine' desktop='games' follow=on
bspc rule -a 'Steam' desktop='games'
bspc rule -a 'streamlink-twitch-gui' desktop='music' follow=on
bspc rule -a 'Zathura' desktop='music' follow=on state=tiled

# Programming
bspc rule -a 'Tk' state=floating

. /home/me/.config/priv-bspwm

bspc wm --adopt-orphans
