#!/usr/bin/bash

if [ -r "$HOME/.dbus/Xdbus" ]; then
  . "$HOME/.dbus/Xdbus"
fi

# settings
BAT='BAT1'
WARN=10
DANGER=5
SHUT=3

# persistent state: ''=none shown, 1=warn shown, 2=danger shown
STATE=
if [[ -f "/tmp/battery-shelve" ]]; then
  STATE=$(cat /tmp/battery-shelve)
fi

# notifications
CAP=$(cat /sys/class/power_supply/$BAT/capacity)
STATUS=$(cat /sys/class/power_supply/$BAT/status)
if [[ $STATUS = 'Discharging' ]]; then
  if [[ $CAP -le $SHUT ]]; then
    /usr/bin/notify-send -u 'critical' 'Battery low' 'Shutting down in 30 seconds due to power loss'
    echo "SHUTDOWN"
    sleep 30
    STATUS=$(cat /sys/class/power_supply/$BAT/status)
    if [[ $STATUS = 'Discharging' ]]; then
      echo "OFF"
      /sbin/shutdown now # requires chmod u+x /sbin/shutdown
    fi
  elif [[ $CAP -le $DANGER && $STATE -ne '2' ]]; then
    /usr/bin/notify-send -u 'critical' 'Battery low' 'Connect to power to avoid emergency shutdown'
    STATE='2'
    echo "DANGER"
  elif [[ $CAP -le $WARN && $STATE -ne '1' && $STATE -ne '2' ]]; then
    /usr/bin/notify-send 'Battery low' "Battery has reached ${WARN}%"
    STATE='1'
    echo "WARN"
  elif [[ $CAP -gt $WARN ]]; then
    STATE=''
    echo "SAFE"
  fi
else
  STATE=''
  echo "Chargin"
fi

echo $STATE > /tmp/battery-shelve
echo $CAP
