#!/bin/bash

##
# Replaces the wallpaper with a blurred one if windows are open
# Dependency: wmutils (lsw) or bspwm (bspc)
##

# gen if it doesn't exist
if [[ ! -f $basepath/blurs/$WALLPAPER ]]; then
  gen_wallpapers $WALLPAPER
fi

if [[ $1 == 'bspwm' ]]; then
  win=$(bspc query -N -n .local | wc -l)
else
  win=$(lsw | wc -l)
fi

if [[ $win -gt 0 ]]; then
  feh --bg-fill $basepath/blurs/$WALLPAPER
elif [[ $win -le 0 ]]; then
  feh --bg-fill $basepath/$WALLPAPER
fi
