#!/bin/bash
if [[ $(id -u) -ne 0 ]]
then
  echo "Running self as root"
  sudo $0
fi

sudo systemctl stop NetworkManager
ip link set wlp2s0 down
macchanger -e wlp2s0
ip link set wlp2s0 up
sudo systemctl start NetworkManager
