#!/bin/bash

##
# Wallpaper manager
# Handles changing wallpaper and running blur listener
# -
# Usage: wallpaper.sh path-to-file.jpg
##

export basepath=$HOME/.theme/wallpapers

# end if not given proper file
if [[ ! -f $basepath/$1 ]]; then
  echo "File does not exist or is directory: $1"
  exit
fi

# set wallpaper and export as env variable
feh --bg-fill $basepath/$1
export WALLPAPER=$1

# kill all previous running instances of self
kill_running() {
  while
    count=$(pgrep -flc ./wallpaper | grep -P "[0-9]+" -o)
    # two because we use functions n such
    [[ $count -gt 2 ]]
  do
    pid=$(pgrep -flo ./wallpaper | grep -P "[0-9]+" -o)
    kill $pid
  done
}

listen_bspwm() {
  while read line
  do
    blur_wallpaper bspwm
  done
}

kill_running
bspc subscribe desktop_focus | listen_bspwm

# run script which blurs/unblurs background


